const types = {
    USER_SIGNED_IN : "USER_SIGNED_IN",
    USER_SIGNED_OUT : "USER_SIGNED_OUT",
    ERROR_GLOBAL : "ERROR_GLOBAL",
    SUCCESS_GLOBAL : "SUCCESS_GLOBAL",
    CLEAR_NOTIFICATION : "CLEAR_NOTIFICATION"
}

export default types